application:
  name: MidgardCharacterBuilder
  description: Midgard Character Builder
  version: 0.1.0
  adminPassword: password

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false

management:
  port: 9080

endpoints:
  sensitive: false
  enabled: true
  health:
    sensitive: false
management.security.enabled: false